# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: manixaist.github.io
email: manixaist@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Developer Journal</h1><h4>Github pages for coding projects</h4><a href='http://xkcd.com/1508/'><img src='http://imgs.xkcd.com/comics/operating_systems.png'/></a> "


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manixaist.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  manixaist

# Build settings
markdown: kramdown  
